/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef GATT_DB_H
#define GATT_DB_H

#include "bg_gattdb_def.h"

extern const struct bg_gattdb_def bg_gattdb_data;

#define temperature_char                       15
#define ota_control                            19
#define ota_data                               21

#endif
