/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef BG_GATTDB_H
#define BG_GATTDB_H

#include "ubt/bg_gattdb_def.h"

extern const struct bg_gattdb_def bg_gattdb_data;

#define gattdb_ShntVltg                         8
#define gattdb_Current                         12
#define gattdb_Power                           16
#define gattdb_Voltage                         20
#define gattdb_TemperatureC                    24
#define gattdb_TemperatureF                    28
#define gattdb_Pressure                        32
#define gattdb_PrTemperatureC                  36
#define gattdb_PrTemperatureF                  40
#define gattdb_Humidity                        44
#define gattdb_HmdtyTempC                      48
#define gattdb_HmdtyTempF                      52
#define gattdb_RGBLightRd                      57
#define gattdb_RGBLightGrn                     61
#define gattdb_RGBLightBlu                     65
#define gattdb_RdSound0                        70
#define gattdb_RdSound16                       74
#define gattdb_RdSound32                       78
#define gattdb_RdSound48                       82
#define gattdb_ThermistorC                     87
#define gattdb_Thermal_1RwC                    91
#define gattdb_Thermal_2RwC                    95
#define gattdb_Thermal_3RwC                    99
#define gattdb_Thermal_4RwC                   103
#define gattdb_Thermal_5RwC                   107
#define gattdb_Thermal_6RwC                   111
#define gattdb_Thermal_7RwC                   115
#define gattdb_Thermal_8RwC                   119
#define gattdb_xgatt_temp0                    124
#define gattdb_xgatt_temp1                    128
#define gattdb_xgatt_temp2                    132
#define gattdb_xgatt_temp3                    136
#define gattdb_xgatt_temp4                    140
#define gattdb_xgatt_temp5                    144
#define gattdb_xgatt_temp6                    148
#define gattdb_xgatt_temp7                    152
#define gattdb_xgatt_temp8                    156
#define gattdb_xgatt_fuel                     160
#define gattdb_xgatt_humidity                 164
#define gattdb_xgatt_barometer                168
#define gattdb_xgatt_lightning                172
#define gattdb_xgatt_rev                      176
#define gattdb_xgatt_fft1                     180
#define gattdb_xgatt_fft2                     184
#define gattdb_xgatt_fft3                     188
#define gattdb_xgatt_fft4                     192
#define gattdb_AnlErrCnt                      197
#define gattdb_AnlErrCd                       201
#define gattdb_AnlDevCd                       205
#define gattdb_AnlTickCnt                     209
#define gattdb_AnlHrtBt                       213
#define gattdb_AnlHrtBt2                      217

#endif
