/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef BG_GATTDB_H
#define BG_GATTDB_H

#include "ubt/bg_gattdb_def.h"

extern const struct bg_gattdb_def bg_gattdb_data;

#define gattdb_ShntVltgRw                       8
#define gattdb_ShntVltg                        12
#define gattdb_CurrentRw                       16
#define gattdb_Current                         20
#define gattdb_PowerRw                         24
#define gattdb_Power                           28
#define gattdb_VoltageRw                       32
#define gattdb_Voltage                         36
#define gattdb_TemperatureRw                   40
#define gattdb_TemperatureC                    44
#define gattdb_TemperatureF                    48
#define gattdb_PressureRw                      52
#define gattdb_Pressure                        56
#define gattdb_PrTemperatureRw                 60
#define gattdb_PrTemperatureC                  64
#define gattdb_PrTemperatureF                  68
#define gattdb_HumidityRw                      72
#define gattdb_Humidity                        76
#define gattdb_HmdtyTempRw                     80
#define gattdb_HmdtyTempC                      84
#define gattdb_HmdtyTempF                      88
#define gattdb_RGBLightRw                      93
#define gattdb_RGBLightRd                      97
#define gattdb_RGBLightGrn                    101
#define gattdb_RGBLightBlu                    105
#define gattdb_RdSound0                       110
#define gattdb_RdSound16                      114
#define gattdb_RdSound32                      118
#define gattdb_RdSound48                      122
#define gattdb_ThermistorRw                   127
#define gattdb_ThermistorC                    131
#define gattdb_Thermal_1Rw                    135
#define gattdb_Thermal_1RwC                   139
#define gattdb_Thermal_2Rw                    143
#define gattdb_Thermal_2RwC                   147
#define gattdb_Thermal_3Rw                    151
#define gattdb_Thermal_3RwC                   155
#define gattdb_Thermal_4Rw                    159
#define gattdb_Thermal_4RwC                   163
#define gattdb_Thermal_5Rw                    167
#define gattdb_Thermal_5RwC                   171
#define gattdb_Thermal_6Rw                    175
#define gattdb_Thermal_6RwC                   179
#define gattdb_Thermal_7Rw                    183
#define gattdb_Thermal_7RwC                   187
#define gattdb_Thermal_8Rw                    191
#define gattdb_Thermal_8RwC                   195
#define gattdb_xgatt_temp0                    200
#define gattdb_xgatt_temp1                    204
#define gattdb_xgatt_temp2                    208
#define gattdb_xgatt_temp3                    212
#define gattdb_xgatt_temp4                    216
#define gattdb_xgatt_temp5                    220
#define gattdb_xgatt_temp6                    224
#define gattdb_xgatt_temp7                    228
#define gattdb_xgatt_temp8                    232
#define gattdb_xgatt_fuel                     236
#define gattdb_xgatt_humidity                 240
#define gattdb_xgatt_barometer                244
#define gattdb_xgatt_lightning                248
#define gattdb_xgatt_rev                      252
#define gattdb_xgatt_fft1                     256
#define gattdb_xgatt_fft2                     260
#define gattdb_xgatt_fft3                     264
#define gattdb_xgatt_fft4                     268
#define gattdb_AnlErrCnt                      273
#define gattdb_AnlErrCd                       277
#define gattdb_AnlDevCd                       281
#define gattdb_AnlTickCnt                     285
#define gattdb_AnlHrtBt                       289

#endif
